/* tslint:disable */
// This file is generated
// Do not edit this file
import * as data from "./data/index";
export * as data from "./data/index";

export type Actions = {
  data: data.ActionData;
}
